name: Run Postman API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman tests - Search
        run: newman run postman_collection.json -d dataset_search.csv \
              -r cli,htmlextra --reporter-htmlextra-export reports/search.html
        continue-on-error: true

      - name: Run Postman tests - Update
        run: newman run postman_collection.json -d dataset_put.csv \
              --env-var JWT_TOKEN=${{ secrets.JWT_TOKEN }} \
              -r cli,htmlextra --reporter-htmlextra-export reports/update.html
        continue-on-error: true

      - name: Run Postman tests - List
        run: newman run postman_collection.json -d page_data.csv \
              -r cli,htmlextra --reporter-htmlextra-export reports/list.html
        continue-on-error: true

      - name: Upload Newman Reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: reports/
